### ISSUE TITLE
Find a solution for UI testing. Automatically tests Ghost websites (different browsers, resolutions screenshots)

### ISSUE THREAD

**Issue by pascalandy** [firepress-org/ghostfire#13]
Here is the scenario I have in mind. I'm looking to snapshot of our live websites.

### 1) Many **Pages to test**

Have a bot to test/navigate many pages:

- 1A) https://play-with-ghost.com/
- 1B) https://play-with-ghost.com/live-demo-discover-ghost-v2/
- 1C) https://play-with-ghost.com/live-demo-firepress-attila-for-barbershops/
- 1D) https://play-with-ghost.com/live-demo-firepress-klimax2-for-barbershops/
- etc.

### 2) Many **Resolutions**

Have the bot do full page screen shots of those pages in many resolutions:

- 2A) 1366px
- 2B) 800px
- 2C) 540px
- 2D) 360px

### 3) Many **OS / browsers**

tests all over again using different OS / browsers

- 3A) Mac Safari
- 3B) Mac Chrome
- 3C) Mac Firefox
- 3D) Windows 10 Explorer
- 3E) Windows 10 Chrome
- 3F) Windows 10 Firefox
- 3G) Windows 8 Explorer
- 3H) Windows 8 Chrome
- 3I) Windows 8 Firefox

### 4) **Screen checks**

Once this whole crawling thing is automatically done, I want to see as quickly as possible if those screenshot looks right and mark this execution test as Done.

**Now there are many combinations to check!**

4 pages X 4 résolutions X 9 OS/Browsers = **72 Tests**!

- Test 01 = screenshots of 1A & 2A & 3A
- Test 02 = screenshots of 1B & 2A & 3A
- Test 03 = screenshots of 1C & 2A & 3A
- ...
- Test 21 = screenshots of 1A& 2B & 3E
- Test 22 = screenshots of 1A& 2B & 3F
- Test 23 = screenshots of 1A& 2B & 3G
- Test 24 = screenshots of 1A& 2B & 3H
- Test 25 = screenshots of 1A& 2B & 3I
- ...
- etc.

### 5) Open issue

The system open an issue (like a ToDo) an tag it as "qa-tests". The batch (72 Tests) should be open within a github issue and labelled as TestUI.

**Comment by pascalandy** [comment]
I can across this post which is promising. But I still don't understand how to write tests.
https://medium.freecodecamp.org/how-to-dockerize-your-end-to-end-acceptance-tests-dbb593acb8e0

**Comment by pascalandy** [comment]
Possible solution 
https://github.com/dominicfraser/CodeceptJSDockerExamples/issues/1#issuecomment-425650061

---

Hey Pascal 🙂

For what you are describing it sounds [Differencify](https://github.com/NimaSoroush/differencify) might be a suitable tool, it allows easy taking and comparison of visual snapshots.

There are some examples in the README, and a link to a couple of blogs Nima wrote, including [Using Differencify in Docker](https://medium.com/@nima.soroush.h/using-differencify-in-docker-and-ci-99e3d1ec057c)

**Comment by pascalandy** [comment]
Looks VERY promising

- https://dev.to/uilicious/taking-the-horror-out-of-ui-testing--1fi6
- https://test.uilicious.com/test/public/

**Comment by PicoCreator** [comment]
Hi @pascalandy, thanks for reaching out to us at uilicious.

Visual comparison is a highly demanded feature, and is on our roadmap - https://trello.com/c/vIDM7Gdf/12-test-visual-difference-across-browsers.

Till then, uilicious is mainly useful for functionality testing - ie: if the JS button click works, if the test is already there - which does not seem to be your main use case. Having mostly static pages linked to one another.

I would suggest instead existing competing testing providers for your use case, who offer visual comparison tools from providers such as crossbrowsertesting, to help get you started, I did up a quick demo on your site here 😅 : http://crossbrowsertesting.com/users/public/i787402668ed5201/screenshots/z2b0f0824e57474d7f1c/comparison

Its respective guide is here : https://help.crossbrowsertesting.com/screenshots/getting-started/taking-automated-screenshots/

One down side though, is that this process does not work for elements that can only be seen behind a button click. Another limitation is that, while it greatly helps in the screenshot and comparison aspect, the triggering of the process and passing/failing is still completely manual. It does however helps. 

Quite a number of our users actually use both existing visual comparison tool, and our testing tool in combination. One for exact pixel and colour checks, the other for functionality, hence its high demand to merge the two. 😎

(apologies for the repeated cross site answering)

**Comment by pascalandy** [comment]
done - https://uilicious.com/

**Comment by pascalandy** [comment]
@PicoCreator as mentioned during our DM, I'll be waiting for freemium version available for open source projects like play-with-ghost. I also think this will be the perfect showcase for your potential customers. 

Cheers!

**Comment by pascalandy** [comment]
To consider as well : https://www.cypress.io/
