### ISSUE TITLE
Set PUID and PGID as Variables

### ISSUE THREAD

**Issue by RicardoVelaC** [firepress-org/ghostfire#22]
I want run another ghostfire docker image in "Docker for Synology". My first work OK, but since last security updates Synology force all user to set your Synology user PUID and PGID in docker ENV variables to get write permission when mount a folder.

Others Docker images fix them adding support to PUID and PGID as ENV variable but in ghostfire image set PUID to 1000 as default value. And you can't modify easily.

Can you add support to change PUID and PGID as ENV variables in docker?

**Comment by pascalandy** [comment]
I'm open to this. Can you do a PR?

**Comment by RicardoVelaC** [comment]
I'm newbie on docker, I will try to push a PR

**Comment by pascalandy** [comment]
OK. Here is my cue.

- Use an ARG. Set user=1000 and grp=1000
- Ensure all layers can read the ENV.
- Then run the container using your own VAR and it should override the ARG values.

**Comment by RicardoVelaC** [comment]
Hey @pascalandy thank for the cue 👍 

I tried with some configurations and built it on my Synology but haven't worked at all.

You can see the last one at [https://github.com/RicardoVelaC/ghostfire/blob/master/Dockerfile](url)

It can built it but when I run on my Synology with my own ENV it uses PUID=1000 and PGID =1000 and does't can write permission.

I check it on Internet and maybe I need to add usermod and groupmod to ENTRYPOINT like said in this post
[https://www.reddit.com/r/docker/comments/9iwe3t/where_can_i_find_out_how_puid_and_pgid_are_used/e6n10md/](url)

What do you think? Thanks for help

**Comment by RicardoVelaC** [comment]
Can you help me with this?
Thanks :-)

**Comment by pascalandy** [comment]
As I didn't got a PR I prefer to close this issue.

REF: https://github.com/firepress-org/ghostfire/blob/master/Dockerfile#L90
