### ISSUE TITLE
Not maintained anymore?

### ISSUE THREAD

**Issue by muratcorlu** [firepress-org/ghostfire#508]
Did you stop maintaining this docker image? I see the latest version here is 5.79.6 which is 2 months old.

**Comment by pascalandy** [comment]
Thank you for reaching out! I'm still actively maintaining this Docker image, and I'm happy to hear that you're using it. I understand your concern about the latest version being 2 months old. I'll make sure to push some new releases soon.

**Comment by muratcorlu** [comment]
I see that still the last version is way behind the latest version of Ghost. Do you suffer from the same issue as the Ghost community image? https://github.com/TryGhost/Ghost/issues/20065

**Comment by pascalandy** [comment]
yes, something break son version 5.82.2
It happens from time to time.
